### ISSUE TITLE
Rank and Perm's

### ISSUE THREAD

**Issue by XAzmon** [SagenKoder/BlueLapiz#5]
**Jr.Mod**
Fungerer som moderator med mindre perms og under opplæring. For andre spillere skal JrMod se ut som en vanlig moderator for å best mulig kjenne på å være moderator. Maks ca 2 uker som denne ranken.
- /ss

**Moderator**
Skal moderere minecraft serveren samt discord og forum. Skal ha minimum tillatelser for å kunne moderere server. Herunder:
- /p
- /v
- /tp
- /w
- /co l (lookup)
- Skal se advarsel i chat om hackere og xray

**Sr.Mod**
Skal være mye det samme som moderatorer men stå som forbilde for moderatorer og lære opp moderatorer. Moderatorer skal kunne spørre dem om hva som helst. Disse skal ha tilgang til nesten alt. Herunder:
- /co rb (rollback)

**Admin**
Har ansvar for moderatorer. Herunder lære opp Sr.Mod og tilføye flere nye mods i staben om det trengs. Har tilgang til så og si alt, inkludert å ranke spillere
- /rank
- /gm

**Founder**
Stian, Alex og Kaj. Har tilgang til alt og overstyrer alle besluttninger gjort av andre i lavere ranks uten spørsmål. Har ansvar for drifting og videreutvikling av serveren og skal ikke trenge å tenke på daglig drift på serveren.

**Comment by SagenKoder** [comment]
Selve rankene er laget, Hvem som skal få tilgang til hva implementeres når de respektive kommandoer blir kodet
